language: ruby
before_install:
  - sudo ./travis-ci/install_kc
bundler_args: --without development
script: "bundle exec rake test"
rvm:
  - 1.9.3
  - jruby-19mode # JRuby in 1.9 mode
  - jruby-head
  - rbx-19mode
matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: jruby-head
    - rvm: rbx-19mode

# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
